
package org.barcelonamedia.cotigclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Corrector Web Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CotigWebService", targetNamespace = "urn:CotigWebService", wsdlLocation = "http://fbminfojobs01/correctorCAU/CotigWebService.asmx?wsdl=0")
public class CotigWebService
    extends Service
{

    private final static URL COTIGWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.barcelonamedia.cotigclient.CotigWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.barcelonamedia.cotigclient.CotigWebService.class.getResource(".");
            url = new URL(baseUrl, "http://fbminfojobs01/correctorCAU/CotigWebService.asmx?wsdl=0");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://fbminfojobs01/correctorCAU/CotigWebService.asmx?wsdl=0', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COTIGWEBSERVICE_WSDL_LOCATION = url;
    }

    public CotigWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CotigWebService() {
        super(COTIGWEBSERVICE_WSDL_LOCATION, new QName("urn:CotigWebService", "CotigWebService"));
    }

    /**
     * 
     * @return
     *     returns CotigWebServiceSoap
     */
    @WebEndpoint(name = "CotigWebServiceSoap")
    public CotigWebServiceSoap getCotigWebServiceSoap() {
        return super.getPort(new QName("urn:CotigWebService", "CotigWebServiceSoap"), CotigWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CotigWebServiceSoap
     */
    @WebEndpoint(name = "CotigWebServiceSoap")
    public CotigWebServiceSoap getCotigWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn:CotigWebService", "CotigWebServiceSoap"), CotigWebServiceSoap.class, features);
    }

}
